### ISSUE TITLE
Threat detected

### ISSUE THREAD

**Issue by TheBudda** [MediaBrowser/MediaBrowser.Android#20]
I just install MediaBrowser.Android and Kaspersky found a threat Emby base.apk HEUR:Trojan-SMS.AndroidOS.Chises.a 
![screenshot_2016-02-11-18-01-15](https://cloud.githubusercontent.com/assets/16983376/12985440/8d56b8a2-d0ea-11e5-961e-1d8415db0b1d.png)

**Comment by LukePulverenti** [comment]
Thanks, some kind of false positive. Just skip it.

**Comment by TheBudda** [comment]
Thanks for the very quick reply. just thought you should see it. I have skipped it  ;- )
